### ISSUE TITLE
Use https only

### ISSUE THREAD

**Issue by Nickbert7** [escabe/pvr.jellyfin#1]
Is it possible to use https only?
My server is only accessible via https and not via http.
It seams that the addon tries to access the live tv stream via http. (see logs line 274)
[kodi.log](https://github.com/escabe/pvr.jellyfin/files/3515571/kodi.log)

Hostname: 'url.to.jellyfin'
HTTPPort: '80'
HTTPSPort: '443'

**Comment by escabe** [comment]
This plugin is currently designed to be used in my own exact setup which is actually mainly HTTP based. If I am ever going to "officially" release anything here, I might add some additional configuration options like Use HTTPS for login, Ignore Server Certificate for login, Use HTTPS for urls, etc. But for now: no this is not configurable.

If you are building from source anyway though, you could of course make two small changes to make this work over HTTPS, on the following two lines:

https://github.com/escabe/pvr.jellyfin/blob/5129f9ea58e292c1efa4375cf8d323d720dd7e4c/src/JellyfinData.cpp#L766

https://github.com/escabe/pvr.jellyfin/blob/5129f9ea58e292c1efa4375cf8d323d720dd7e4c/src/JellyfinData.cpp#L773

Replace `m_strBaseHTTPUrl` with `m_strBaseHTTPSUrl`.

**Comment by Nickbert7** [comment]
Thanks for the information.
I found out that the NextPVR plugin seems to have some issues on my server.
With an m3u8 tuner it is working fine without the changes.
Maybe this is becaus of the HTTPS redirect from port 80 to 443 on my reverse-proxy
